kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: system:{{ include "nifcloud-cloud-controller-manager.name" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:{{ include "nifcloud-cloud-controller-manager.name" . }}
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: {{ include "nifcloud-cloud-controller-manager.name" . }}
    namespace: {{ .Release.Namespace }}
