apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: system:{{ include "nifcloud-cloud-controller-manager.name" . }}-auth-reader
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader
subjects:
  - kind: ServiceAccount
    name: {{ include "nifcloud-cloud-controller-manager.name" . }}
    namespace: {{ .Release.Namespace }}
