apiVersion: v1
entries:
  nifcloud-cloud-controller-manager:
  - apiVersion: v2
    appVersion: v1.0.0
    created: "2023-08-05T15:28:29.111866+09:00"
    description: A Helm chart for NIFCLOUD cloud controller manager
    digest: ab036eb22e592ff952cb46c74c627b426a5f8403b40504e7430a628233bba59e
    name: nifcloud-cloud-controller-manager
    type: application
    urls:
    - nifcloud-cloud-controller-manager-1.0.0.tgz
    version: 1.0.0
generated: "2023-08-05T15:28:29.111137+09:00"
