name: CI

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Diff mod
        run: go mod tidy && git diff --exit-code go.mod go.sum

      - name: Install ginkgo
        run: go install github.com/onsi/ginkgo/v2/ginkgo

      - name: Build
        run: make build

      - name: Test
        run: make test
